version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run: 
          command: 'sudo npm install -g mocha'
      - run: 
          command: 'sudo npm install -g mocha-junit-reporter'  
      
      - run: 
          command: 'mocha test --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml'
      
      - store_test_results:
                path: reports
      - store_artifacts:
          path: ./reports/mocha/test-results.xml
workflows:
  workflow:
    jobs:
      - test