version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: 'sudo npm install -g npm@latest'
      - run: 'sudo npm install -g mocha'
      - run: 'sudo npm install -g mocha-junit-reporter'  
      
      - run: 'npm install'
      - run: 'mocha test --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml'
      
      - store_test_results:
                path: reports
      - store_artifacts:
          path: ./reports/mocha/test-results.xml
workflows:
  workflow:
    jobs:
      - test